questions_data = {
    "Intérêts et activités": {
        "🔧 Réaliste": [
            "Planter, entretenir des arbres, des arbustes, des fleurs ou cultiver le sol.",
            "Faire de la couture.",
            "Effectuer des réparations électriques ou électroniques.",
            "Réparer des automobiles.",
            "Fabriquer des objets avec du bois.",
            "Conduire un camion ou un tracteur.",
            "Faire des déménagements.",
            "Entretenir ou réparer de la plomberie ou des systèmes de ventilation.",
            "Travailler avec des animaux et en prendre soin.",
            "Travailler à l’extérieur (exposer à la pluie, au soleil, au froid).",
            "Travailler avec de la machinerie.",
            "Préparer des repas, des banquets.",
            "Travailler avec des outils tels que tournevis, ciseaux, pince, etc.",
            "Effectuer des travaux de peinture.",
            "Suivre un cours de dessin mécanique."
        ],
        "🧠 Investigateur": [
            "Lire des revues scientifiques ou spécialisées.",
            "Faire des expériences sur le comportement des animaux.",
            "Effectuer des analyses en laboratoire.",
            "Suivre des cours de sciences.",
            "Établir un diagnostic de maladie chez des patients.",
            "Expérimenter de nouvelles cultures végétales.",
            "Créer une nouvelle source d’énergie.",
            "Concevoir un barrage électrique, un pont, une autoroute, etc.",
            "Résoudre des problèmes mathématiques.",
            "Faire des recherches scientifiques pour satisfaire ma curiosité.",
            "Produire un rapport sur l’évolution économique d’une région.",
            "Concevoir un plan de reboisement.",
            "Planifier des soins ou des traitements à donner à des patients.",
            "Faire des recherches sur les civilisations anciennes.",
            "Faire de la programmation informatique."
        ],
        "🎨 Artistique": [
            "Écrire des romans, des articles de journaux.",
            "Dessiner des meubles, des plans de maison, des décors, etc.",
            "Interpréter ou mettre en scène une pièce de théâtre.",
            "Jouer dans un orchestre.",
            "Créer des pièces d’artisanat.",
            "Imaginer de nouvelles façons de faire les choses.",
            "Embellir l’environnement.",
            "Créer une nouvelle coupe de cheveux ou de nouveaux vêtements.",
            "Faire de la photographie publicitaire ou artistique.",
            "Concevoir et réaliser des arrangements de fleurs.",
            "Imaginer une bande dessinée.",
            "Peindre des tableaux pour une exposition.",
            "Décorer des vitrines de magasins.",
            "Écrire des critiques de pièces de théâtre, de films, de livres, etc.",
            "Apprendre des langues."
        ],
        "🤝 Social": [
            "S’engager dans des organismes sociaux ou communautaires.",
            "Rencontrer des gens pour les aider à résoudre leurs problèmes personnels.",
            "Travailler dans une garderie d’enfants.",
            "Enseigner aux enfants, aux adolescents, aux adultes.",
            "Aider les gens à prendre conscience de leurs possibilités.",
            "Animer un groupe.",
            "Agir comme hôte / hôtesse lors d’un congrès.",
            "Tenir un kiosque d’information.",
            "Offrir un service d’aide téléphonique.",
            "Consulter les gens sur leurs besoins (sondage, enquête, etc.).",
            "S’occuper des personnes handicapées physiquement.",
            "Soigner un malade.",
            "Aider les délinquants à se réhabiliter.",
            "Organiser des loisirs.",
            "Échanger des idées avec d’autres personnes."
        ],
        "🚀 Entreprenant": [
            "Vendre un produit ou une idée.",
            "Mettre sur pied son propre commerce.",
            "Donner des conférences.",
            "Acheter pour le compte d’un grand magasin.",
            "Marchander.",
            "Diriger du personnel.",
            "Défendre une cause.",
            "Faire de la sélection de candidats.",
            "S’engager à fond dans des activités sociales au travail ou dans son quartier.",
            "Diriger une entreprise financière.",
            "Lancer un nouveau produit.",
            "Fonder un club de consommateurs, une association de protection de l’environnement, une activité de récupération de papier.",
            "Gérer un projet spécial.",
            "Faire de la politique (municipal, scolaire, provincial).",
            "Lancer un concours de promotion, une campagne de publicité."
        ],
        "📊 Conventionnel": [
            "Établir des comptes-rendus des dépenses.",
            "Préparer des procès-verbaux de réunions.",
            "Tenir une caisse dans un établissement commercial ou financier.",
            "Faire un inventaire et passer des commandes.",
            "Manipuler un appareil à traitement de textes.",
            "Maintenir un système de classement (archive, bibliothèque, bureau, etc.).",
            "Garder mon espace de travail en ordre.",
            "Faire des opérations mathématiques pour préparer des rapports ou faire la tenue de livres.",
            "S’adonner à des activités régulières.",
            "Classer des lettres, des rapports, des dossiers.",
            "Recevoir et faire des appels téléphoniques.",
            "Vérifier des rapports financiers.",
            "Faire fonctionner toutes sortes de machines de bureau.",
            "Effectuer des tâches clairement définies.",
            "Dactylographier ou réviser des lettres ou des rapports."
        ]
    },
    "Intérêts et occupations": {
        "🔧 Réaliste": [
            " Mécanicien / mécanicienne d’auto",
 "Éleveur / éleveuse de bétails",
"Technicien / technicienne dentaire",
 "Travailleur / travailleuse de la construction (menuiserie)",
 "Couturier / couturière en usine",
 "Technicien / technicienne en aménagement de la faune",
 "Horloger / horlogère",
 "Technicien / technicienne du meuble et du bois ouvré (ébéniste)",
 "Plombier / plombière",
 "Technicien / technicienne en mécanique du bâtiment",
 "Conducteur / conductrice d’autobus",
 "Technicien / technicienne en entretien d’aéronefs",
 "Réparateur / réparatrice de télévision",
 "Ingénieur / ingénieure civil",
 "Cuisinier / cuisinière"
        ],
        "🧠 Investigateur": [
            "Ingénieur / ingénieure en chimie, physique",
 "Technicien / technicienne en laboratoire médical",
 "Chercheur / chercheuse scientifique",
 "Technicien / technicienne en radiologie (rayon X)",
 "Biologiste",
 "Technicien / technicienne en informatique",
 "Médecin ou vétérinaire",
 "Technicien / technicienne en transformation des produits forestiers",
 "Météorologiste",
 "Astronome (étudie le mouvement des astres dans le ciel)",
 "Technicien / technicienne en dessin conception mécanique",
 "Économiste",
 "Technicien / technicienne en procédés métallurgiques (spécialiste dans la transformation des métaux)",
 "Botaniste",
 "Technicien / technicienne en chimie analytique (analyse de nouveaux produits chimiques)"
        ],
        "🎨 Artistique": [
            "Musicien / musicienne",
 "Écrivain / écrivaine",
 "Fleuriste",
 "Journaliste",
 "Décorateur / décoratrice d’intérieur",
 "Compositeur / compositrice (musique)",
 "Mannequin",
 "Photographe",
 "Graphiste",
 "Directeur de publicité",
 "Architecte",
 "Interprète",
 "Chanteur / chanteuse",
 "Comédien / comédienne",
 "Professeur de dessin"
        ],
        "🤝 Social": [
            "Infirmier / infirmière auxiliaire",
 "Agent / agente à l’aide sociale",
 "Travailleur / travailleuse sociale",
 "Barmaid / barman",
 "Professeur à l’élémentaire",
 "Technicien / technicienne en loisirs",
 "Technicien / technicienne en garderie d’enfants",
 "Orthophoniste, orthopédagogue (correction des troubles de l’apprentissage)",
 "Esthéticien / esthéticienne",
 "Technicien / technicienne policier / policière",
"Médecin généraliste (de famille)",
 "Directeur / directrice du personnel",
 "Bibliothécaire",
 "Technicien / technicienne en hygiène dentaire",
 "Technicien / technicienne en réadaptation physique",
        ],
        "🚀 Entreprenant": [
            "Agent / agente de publicité (marketing)",
 "Avocat / avocate",
 "Agent / agente de bord",
 "Chef de rayons de supermarché",
 "Commis-vendeur / vendeuse",
 "Directeur / directrice d’une entreprise",
 "Politicien / politicienne",
 "Directeur / directrice des ventes",
 "Vendeur / vendeuse d’assurances",
 "Gérant / gérante d’hôtel",
 "Technicien / technicienne en tourisme",
 "Propriétaire d’un commerce",
 "Courtier / coutière en immeubles",
 "Acheteur / acheteuse",
 "Agent / agente de voyage"
        ],
        "📊 Conventionnel": [
            "Commis-comptable",
 "Technicien / technicienne en finance (comptabilité)",
 "Opérateur / opératrice en informatique",
 "Secrétaire de service juridique, médical",
 "Archiviste médical",
 "Commis aux renseignements",
 "Bibliotechnicien / bibliotechnicienne",
 "Expert / experte en impôt",
 "Caissier / caissière de banque",
 "Réceptionniste",
 "Commis au service de la paie",
 "Gérant / gérante du service de crédits",
 "Commis de bureau",
 "Sténodactylo, opérateur (-trice) de saisie",
 "Technicien / technicienne judiciaire (aux greffes)"
        ]

    },
  
    "Aptitudes": {
        "🔧 Réaliste": [
            {"question": "Ma capacité à soulever des poids lourds est :", "values": [0, 0.5, 1]},
            {"question": "Ma capacité à utiliser des outils, des objets, des machines avec précision est :", "values": [0, 0.5, 1]},
            {"question": "Mon habileté à conduire un gros véhicule (camion, autobus) est :", "values": [0, 0.5, 1]},
            {"question": "Mon aptitude à lire des plans est :", "values": [0, 0.5, 1]},
            {"question": "Mon habileté dans les mouvements demandant à voir et à manipuler en même temps est :", "values": [0, 0.5, 1]},
            {"question": "Ma capacité à comprendre le fonctionnement des éléments de base de tout ouvrage mécanique, électrique (turbine, moteur, pompe…) est :", "values": [0, 0.5, 1]},
            {"question": "La rapidité de mes réflexes est :", "values": [0, 0.5, 1]},
            {"question": "Mon habileté à faire des réparations est :", "values": [0, 0.5, 1]},
            {"question": "Ma capacité à m’occuper d’élevage d’animaux est :", "values": [0, 0.5, 1]},
            {"question": "Ma capacité à installer et à manipuler divers outils, machines ou appareils est :", "values": [0, 0.5, 1]},
            
        ],
        "🧠 Investigateur": [
            {"question": "Mes aptitudes en mathématiques sont :", "values": [0, 0.5, 1]},
            {"question": "Mes capacités en sciences sont :", "values": [0, 0.5, 1]},
            {"question": "Ma capacité à me concentrer sur une tâche abstraite est :", "values": [0, 0.5, 1]},
            {"question": "Ma capacité d’analyse est :", "values": [0, 0.5, 1]},
            {"question": "Ma capacité de synthèse est :", "values": [0, 0.5, 1]},
            {"question": "Mon talent à rédiger clairement un texte est :", "values": [0, 0.5, 1]},
            {"question": "Ma capacité à saisir et comprendre des directives rapidement est :", "values": [0, 0.5, 1]},
            {"question": "Mon habileté à apprendre des nouveaux sujets avec facilité et avec aise est :", "values": [0, 0.5, 1]},
            {"question": "Mon habileté à solutionner des problèmes abstraits est :", "values": [0, 0.5, 1]},
            {"question": "Mon habileté à faire des travaux de laboratoire est :", "values": [0, 0.5, 1]},
        ],

        "🎨 Artistique": [
            {"question": "Ma capacité à me représenter la forme d’objets en deux ou trois dimensions est :", "values": [0, 0.5, 1]},
            {"question": "Ma capacité à apprendre des langues, y compris ma langue maternelle est :", "values": [0, 0.5, 1]},
            {"question": "Mon aptitude en arts plastiques (dessin, sculpture, peinture, etc.) est :", "values": [0, 0.5, 1]},
            {"question": "Mon aptitude dans les arts de la scène (théâtre, danse, musique, etc.) est :", "values": [0, 0.5, 1]},
            {"question": "Ma capacité d’inventer, de créer, de concevoir est :", "values": [0, 0.5, 1]},
            {"question": "Ma capacité à accepter la critique est :", "values": [0, 0.5, 1]},
            {"question": "Ma capacité à travailler par moi-même est :", "values": [0, 0.5, 1]},
            {"question": "Mon aptitude à exprimer concrètement mes idées créatrices dans le médium de mon choix (musique, écriture, danse, dessin, etc.) est :", "values": [0, 0.5, 1]},
            {"question": "Mon aptitude à tolérer l’insécurité (peur du lendemain) est :", "values": [0, 0.5, 1]},
            {"question": "Mon habileté à observer les légères différences de forme ou de teinte est :", "values": [0, 0.5, 1]},
        ],
        "🤝 Social": [
            {"question": "Mon aptitude à travailler en équipe est :", "values": [0, 0.5, 1]},
            {"question": "Mon sens de l’organisation est :", "values": [0, 0.5, 1]},
            {"question": "Ma faculté de prévoir, de deviner (intuition) est :", "values": [0, 0.5, 1]},
            {"question": "Ma capacité à diriger des interactions dans un groupe (animation) est :", "values": [0, 0.5, 1]},
            {"question": "Ma capacité à maintenir des relations suivies avec les gens est :", "values": [0, 0.5, 1]},
            {"question": "Mon aptitude à être touché/e par les émotions des autres tout en demeurant objectif (empathie) est :", "values": [0, 0.5, 1]},
            {"question": "Ma capacité à réagir correctement devant les situations qui se présentent (équilibre émotionnel) est :", "values": [0, 0.5, 1]},
            {"question": "Ma capacité à aider les autres, à les comprendre, à les écouter est :", "values": [0, 0.5, 1]},
            {"question": "Ma capacité à expliquer les choses clairement est :", "values": [0, 0.5, 1]},
            {"question": "Ma capacité à communiquer avec les autres est :", "values": [0, 0.5, 1]},
        ],

        "🚀 Entreprenant": [
            {"question": "Ma facilité à m’exprimer en public est :", "values": [0, 0.5, 1]},
            {"question": "Mon talent pour vendre est :", "values": [0, 0.5, 1]},
            {"question": "Mon sens des affaires est :", "values": [0, 0.5, 1]},
            {"question": "Mon habileté à diriger, à mener les autres est :", "values": [0, 0.5, 1]},
            {"question": "Ma capacité à prendre une décision seul/e est :", "values": [0, 0.5, 1]},
            {"question": "Mon habileté à me faire valoir en société est :", "values": [0, 0.5, 1]},
            {"question": "Mon aptitude à défendre une cause est :", "values": [0, 0.5, 1]},
            {"question": "Ma capacité à être le premier/ière à proposer ou à faire quelque chose est :", "values": [0, 0.5, 1]},
            {"question": "Mon talent pour persuader les gens est :", "values": [0, 0.5, 1]},
            {"question": "Ma capacité à demeurer enthousiaste et énergique même en situation difficile est :", "values": [0, 0.5, 1]},
        ],
        "📊 Conventionnel": [
            {"question": "Ma capacité à me conformer aux règles établies est :", "values": [0, 0.5, 1]},
            {"question": "Mon aptitude à travailler avec précision est :", "values": [0, 0.5, 1]},
            {"question": "Ma capacité à disposer les choses selon le rang, la place qui leur convient est :", "values": [0, 0.5, 1]},
            {"question": "Mon aptitude en français est :", "values": [0, 0.5, 1]},
            {"question": "Mon aptitude à travailler avec les chiffres est :", "values": [0, 0.5, 1]},
            {"question": "Ma capacité à observer les détails est :", "values": [0, 0.5, 1]},
            {"question": "Ma capacité à m’adapter à un travail routinier est :", "values": [0, 0.5, 1]},
            {"question": "Ma capacité à tenir des dossiers et des registres à jour est :", "values": [0, 0.5, 1]},
            {"question": "Ma capacité à comprendre et à exécuter des instructions est :", "values": [0, 0.5, 1]},
            {"question": "Mon aptitude à comprendre les structures administratives est :", "values": [0, 0.5, 1]},
        ],
        
    },
    "Personnalités": {
        "🔧 Réaliste": [
            "Je suis conformiste, je me plie facilement aux règlements du milieu où je vis.",
 "Généralement, j’évite de me faire remarquer.",
 "J’aime les choses matérielles, concrètes.",
 "Dans mon travail ou autres, je me montre persistant/e.",
 "Je démontre un esprit d’équipe pratique et je préfère agir plutôt que de discuter trop longuement de ce que l’on va faire.",
 "Je suis d’un naturel réservé ; pour savoir mon opinion, on doit me le demander.",
 "Je suis porté/e à ménager et à prendre soin de mes biens.",
 "Je suis stable dans mes opinions, ma façon de vivre, mes amitiés.",
 "Je me présente toujours au naturel, tel que je suis.",
 "Avec mon entourage, je suis franc/che et sincère."
        ],
        "🧠 Investigateur": [
            "J’analyse les idées, les événements, ce qui se passe autour de moi.",
 "J’ai l’esprit critique et n’accepte pas facilement n’importe quelle idée.",
 "Je suis d’un naturel très curieux sur à peu près tout.",
 "Je tiens à mon indépendance sur le plan des idées, du travail, etc.",
 "Les gens me considèrent comme une personne intellectuelle plutôt qu’émotive.",
 "J’ai l’esprit inventif : il m’arrive souvent de trouver une solution originale et efficace à un problème.",
 "Dans mes activités scolaires ou autres, je me montre méthodique et rationnel/le.",
 "J’aime la précision dans tout ce que je fais.",
 "Je demeure réservé/e dans l’expression de mes opinions, de mes sentiments et de mes actes.",
 "Avant toute décision, je réunis le maximum d’information possible.",
        ],
        "🎨 Artistique": [
            "Mes amis/es me considèrent compliqué/e.",
 "Dans mes diverses activités, je manque souvent d’ordre.",
 "Dans mes travaux, je fais preuve d’originalité, d’imagination et d’intuition.",
 "Je suis d’un caractère impulsif.",
 "Mes émotions sont généralement intenses.",
 "Je suis porté/e à tout idéaliser et à chercher la perfection.",
 "J’agis et je pense souvent de façon non conformiste, c’est-à-dire différemment des autres.",
 "J’exprime mes sentiments par l’entremise de la musique, des beaux-arts, de la poésie, etc.",
 "Les lendemains ne m’inquiètent pas : je vis au jour le jour.",
 "J’ai besoin de beaucoup de liberté d’action dans tout ce que j’entreprends.",
        ],
        "🤝 Social": [
            "Quand un problème se pose, je préfère le régler par la discussion et l’entente avec les gens qui m’entourent.",
 "Je sais me montrer souple, conciliant/e.",
 "Mes amis/es me considèrent comme bienveillant et compréhensif/ve.",
 "Généralement, les gens peuvent compter sur ma coopération.",
 "Les gens me qualifient de sociable et sympathique.",
 "Je suis d’un naturel serviable.",
 "J’accepte et j’assume des responsabilités.",
 "On me considère généreux/se.",
 "Dans la majorité des circonstances, je suis perspicace, clairvoyant/e.",
 "Dans l’action comme dans la façon de m’exprimer, je montre de la délicatesse.",
        ],
        "🚀 Entreprenant": [
            "L’ambition ne m’effraie pas.",
 "Je suis un/e optimiste né/e.",
 "Je suis sociable et populaire ; je parle à tout le monde.",
 "Je défends toujours mes opinions.",
 "Il m’arrive souvent de me montrer autoritaire.",
 "L’aventure m’attire beaucoup.",
 "Généralement, je suis sûr/e de moi.",
 "Mes impulsions me dictent souvent ma conduite.",
 "J’aime être responsable d’activités.",
 "Même dans des situations critiques ou tendues, je sais prendre l’initiative nécessaire.",
        ],
        "📊 Conventionnel": [
            "Je suis maître de moi, d’un calme exemplaire.",
 "J’obéis facilement aux règlements et aux ordres.",
 "Dans mes travaux, je suis persistant/e et consciencieux/se.",
 "Je m’efforce de me montrer compétent dans ce qu’on exige de moi.",
 "L’esprit concret et pratique me guide.",
 "J’agis méthodiquement dans tout ce que je fais.",
 "Je travaille avec beaucoup de soin.",
 "D’une journée à l’autre, j’aime exécuter des tâches semblables.",
 "Je suis timide et je préfère garder pour moi mes sentiments, mes émotions et mes idées.",
 "J’aime recevoir des instructions bien claires qui me permettent de savoir exactement ce qu’on attend de moi.",
        ]

    },
  
}
